name: Build and Push Docker Image

on: 
  push:
    branches:
      - 'main'
jobs:
  build-push-to-registry:
    name: build and push docker image to registry
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: check repository
        uses: actions/checkout@v4
      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: build and push minecraft-server-fabric-vanilla-1.21 docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfiles/fabric-vanilla-1.21.Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/minecraft-server-fabric-vanilla-1.21:latest, ${{secrets.DOCKERHUB_USERNAME}}/minecraft-server-fabric-vanilla-1.21:${{ github.sha }}
